### ISSUE TITLE
View port occasional black screen when rotating.

### ISSUE THREAD

**Issue by bartoszek** [patmo141/cut_mesh#33]
Sometimes while rotating/zooming during first phase of `polytrim` i got this error message in console.

`Traceback (most recent call last):
  File "/home/bartus/.config/blender/2.78/scripts/addons/cut_mesh/modaloperator.py", line 114, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "/home/bartus/.config/blender/2.78/scripts/addons/cut_mesh/op_polytrim/polytrim_ui_draw.py", line 17, in draw_postpixel
    self.draw_2d(context)
  File "/home/bartus/.config/blender/2.78/scripts/addons/cut_mesh/op_polytrim/polytrim_ui_draw.py", line 24, in draw_2d
    self.knife.draw(context)
  File "/home/bartus/.config/blender/2.78/scripts/addons/cut_mesh/op_polytrim/polytrim_datastructure.py", line 1726, in draw
    common_drawing.draw_3d_points(context,self.pts, 4, color = (1,1,1,1)) 
  File "/home/bartus/.config/blender/2.78/scripts/addons/cut_mesh/common_drawing.py", line 121, in draw_3d_points
    bgl.glVertex2f(*vector2d)  
TypeError: glVertex2f() argument after * must be an iterable, not NoneType`

When the issue occurs viewport goes black, beside the blue knife line. Even the white way-point on the knife path gets hidden, and to bring everything back I have to zoom-out/rotate-back the view.

**Comment by patmo141** [comment]
thanks for the report, I think I see the problem.  Will try and fix here shortly

**Comment by ooMICAHoo** [comment]
The code has changed a bit since this error was posted, but I think the error still exists as this happened while I was zooming/changing the view.

![zoom-scroll_error](https://user-images.githubusercontent.com/17998462/41995945-50e67f78-7a21-11e8-9050-4c3c0b88ba68.PNG)

**Comment by ooMICAHoo** [comment]
I believe I fixed it! Let me know if I didn't.
